---
title: "Ktimatologio Aggelw"
output:
  html_document:
    theme: united
    highlight: tango
    toc: true

---


```{r libraries, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(sf)
library(ggplot2)
library(tmap)
library(leaflet)
library(readr)
library(kableExtra)
```


```{r message=FALSE, warning=FALSE, include=FALSE}

## read csvs
dex_csv <- read_csv("../dexameni.csv")

## read shapefiles
dexameni <- read_sf("../dexameni_poly.shp")
dexamenoi_pts <- read_sf("../dexam_points.shp")
farmakeio <- read_sf("../farmakeio.shp")
mandra <- read_sf("../mandra.shp")
tzitzi <- read_sf("../tzitzi.shp")
ag_apostoloi <- read_sf("../ag_apostoloi.shp")
koumpouloi <- read_sf("../koumpouloi.shp")

```




## Dexameni

**Total Area:** 1727 m2  
**KAEK:** 480090202005
```{r dexameni, echo=FALSE, message=FALSE, warning=FALSE}
dexamenoi_pts <- dexamenoi_pts[, c(4, 1, 2, 3)]
dexamenoi_pts <- dexamenoi_pts[1:3]
dexamenoi_pts %>% st_drop_geometry() %>% kbl %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

tmap_options(check.and.fix = T)
tmap_mode("view")

tm_basemap("OpenStreetMap")  + tm_shape(dexameni) + tm_fill("#31a354") +
  tm_polygons() + tm_shape(dexamenoi_pts) + tm_dots()
```

## Mandra (aka spiti amfissa)

**Total Area:** 477 m2
```{r Mandra, echo=FALSE, message=FALSE, warning=FALSE}

tmap_options(check.and.fix = T)
tmap_mode("view")

tm_basemap("OpenStreetMap") + tm_shape(mandra) + tm_fill("#756bb1") + tm_polygons()
```

## Farmakeio

**Total Area:** 101 m2
```{r Farmakeio, echo=FALSE, message=FALSE, warning=FALSE}

tmap_options(check.and.fix = T)
tmap_mode("view")

tm_basemap("OpenStreetMap") + tm_shape(farmakeio) + tm_fill("#756bb1") + tm_polygons()
```

## Koumpouloi

**Total Area:** 792 m2
```{r koumpouloi, echo=FALSE, message=FALSE, warning=FALSE}

tmap_options(check.and.fix = T)
tmap_mode("view")

tm_basemap("OpenStreetMap") + tm_shape(koumpouloi) + tm_fill("#31a354") + tm_polygons()
```

## Agioi Apostoloi

**Total Area:** 1987 m2
```{r agioi, echo=FALSE, message=FALSE, warning=FALSE}

tmap_options(check.and.fix = T)
tmap_mode("view")

tm_basemap("OpenStreetMap") + tm_shape(ag_apostoloi) + tm_fill("#31a354") + tm_polygons()
```

## Tzitzi

**Total Area:** 1700 m2
```{r tzti, echo=FALSE, message=FALSE, warning=FALSE}

tmap_options(check.and.fix = T)
tmap_mode("view")

tm_basemap("OpenStreetMap") + tm_shape(tzitzi) + tm_fill("#31a354") + tm_polygons()
```
